#!/bin/bash

SO_PATH="$HOME/SSB-BYPASS/bypassb.cpython-312.so"
URL="https://raw.githubusercontent.com/dilutecodes/SSB-BYPASS/main/bypassb.cpython-312.so"

mkdir -p "$HOME/SSB-BYPASS"

if [ ! -f "$SO_PATH" ]; then
    echo "[*] bypassb.so not found. Downloading..."
    curl -L -o "$SO_PATH" "$URL"
    if [ $? -ne 0 ]; then
        echo "[!] Download failed"
        exit 1
    fi
else
    echo "[*] bypassb.so already exists."
fi

python -c "import bypassb"